In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals


import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.12604596, 0.18274342, 0.09165001, 0.08584231, 0.07713233,
        0.05726498, 0.05751849, 0.12824458, 0.10558274, 0.08797523]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.860066

In [14]:
model.compile(optimizer='adagrad',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 2s 36us/sample - loss: 0.0842 - accuracy: 0.9754
Epoch 2/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0796 - accuracy: 0.9767
Epoch 3/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0787 - accuracy: 0.9779
Epoch 4/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0789 - accuracy: 0.9773
Epoch 5/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0787 - accuracy: 0.9769
Epoch 6/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0773 - accuracy: 0.9772
Epoch 7/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0779 - accuracy: 0.9776
Epoch 8/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0771 - accuracy: 0.9776
Epoch 9/10
60000/60000 [==============================] - 2s 33us/sample - loss: 0.0773 - accuracy: 0.9779
Epoch 10/10
60

In [15]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0774 - accuracy: 0.9759


[0.077365882361494, 0.9759]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.7775214e-06, 2.1200778e-07, 5.8084566e-05, 4.9587409e-04,
        1.7050207e-09, 1.0310017e-06, 1.3847021e-10, 9.9942327e-01,
        1.6101353e-06, 1.8292361e-05],
       [7.2365192e-06, 4.8177415e-05, 9.9987054e-01, 5.5735829e-05,
        1.6934277e-11, 2.2823460e-06, 8.5385427e-06, 1.9773572e-11,
        7.4363288e-06, 1.1999643e-10],
       [3.8173384e-06, 9.9391574e-01, 1.2627323e-03, 1.2169211e-04,
        1.5102653e-04, 1.9276398e-04, 2.4419528e-04, 3.2455870e-03,
        8.3998829e-04, 2.2473281e-05],
       [9.9973565e-01, 1.3350994e-08, 4.3296910e-05, 1.3020258e-06,
        2.5441653e-07, 3.2307194e-05, 2.2206505e-05, 1.5296122e-04,
        3.3448674e-07, 1.1525638e-05],
       [1.9110669e-04, 7.6036855e-07, 2.6382634e-04, 8.0831078e-06,
        9.7731459e-01, 1.2192727e-05, 1.0677170e-04, 8.2742062e-04,
        3.9634971e-05, 2.1235537e-02]], dtype=float32)>